/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Sim' at '2/19/17 10:54 PM' with Gradle 2.14.1
 *
 * @author Sim, @date 2/19/17 10:54 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
